### ISSUE TITLE
Resolve  'Enclosed Biosphere II' bug

### ISSUE THREAD

**Issue by dosaki** [Thomahawk2k/Colonize-Unlimited#4]
There should be no `Enclosed Biosphere II` tech.

> I think there is something wrong with the biosphere tech.
> I can't research "Enclosed Biosphere II" unlocks building: "Enclosed Biosphere Center" 
> If i try to click it in the society research list, so that the research starts, nothing happens and i can click it indefinitly without change. 

The one below could be related as well:

> I noticed that with some of the new techs, they would not appear. I cheated and researched through all the tech to see, and I would get many of the "repeatable" technologies before I got to controllable solar winds, and those other techs. Some repeatable techs I got 10x before I saw any more unique ones. Also, the "Closed Biosphere" tech will appear more than once. If you click on it AFTER it's already been researched, it does nothing but send you back to the main tech screen.

**Comment by dosaki** [comment]
Is this related? 

```
I noticed that with some of the new techs, they would not appear. I cheated and researched through all the tech to see, and I would get many of the "repeatable" technologies before I got to controllable solar winds, and those other techs. Some repeatable techs I got 10x before I saw any more unique ones. Also, the "Closed Biosphere" tech will appear more than once. If you click on it AFTER it's already been researched, it does nothing but send you back to the main tech screen.
```

**Comment by Thomahawk2k** [comment]
Duplicate 'Enclosed biosphere' has been removed but some testing may be needed...

**Comment by dosaki** [comment]
I'll close this, then. We can re-open if the bug comes back.
